packages:
  - extension
  - docs
  - packages/*

catalog:
  "@egoist/tailwindcss-icons": ^1.9.0
  "@fontsource-variable/jetbrains-mono": ^5.2.8
  "@iconify-json/lucide": ^1.2.70
  "@tailwindcss/typography": ^0.5.19
  "@tailwindcss/vite": ^4.1.14
  "@tanstack/vue-query": ^5.90.5
  "@total-typescript/ts-reset": ^0.6.1
  "@vueuse/core": ^13.9.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  daisyui: ^5.3.7
  es-toolkit: ^1.40.0
  pinia: ^3.0.3
  reka-ui: ^2.5.1
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.14
  tw-animate-css: ^1.4.0
  type-fest: ^5.2.0
  vee-validate: ^4.15.1
  vite: npm:rolldown-vite@latest
  vite-plugin-vue-devtools: ^8.0.3
  vue: ^3.5.22
  vue-router: ^4.6.3
