packages:
  - extension
  - docs
  - packages/*

catalog:
  "@antfu/eslint-config": ^7.6.1
  "@codemirror/lang-json": ^6.0.2
  "@codemirror/theme-one-dark": ^6.1.3
  "@commitlint/cli": ^20.4.2
  "@commitlint/config-conventional": ^20.4.2
  "@commitlint/types": ^20.4.0
  "@egoist/tailwindcss-icons": 1.9.0
  "@fontsource-variable/inter": ^5.2.8
  "@fontsource-variable/jetbrains-mono": ^5.2.8
  "@formkit/auto-animate": ^0.9.0
  "@iconify-json/lucide": ^1.2.95
  "@tailwindcss/typography": 0.5.19
  "@tailwindcss/vite": ^4.2.1
  "@tanstack/vue-query": ^5.92.9
  "@tanstack/vue-virtual": ^3.13.19
  "@total-typescript/ts-reset": ^0.6.1
  "@types/node": ^24.11.0
  "@vitejs/plugin-vue": ^6.0.4
  "@vitejs/plugin-vue-jsx": ^5.1.4
  "@vitest/browser-playwright": ^4.0.18
  "@vueuse/core": ^14.2.1
  "@webext-core/messaging": ^2.3.0
  "@wxt-dev/auto-icons": ^1.1.1
  baseline-browser-mapping: ^2.10.0
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  codemirror: ^6.0.2
  codemirror-json-schema: ^0.8.1
  es-toolkit: ^1.44.0
  eslint: ^10.0.2
  eslint-plugin-better-tailwindcss: ^4.3.1
  lefthook: ^2.1.1
  lucide-vue-next: ^0.575.0
  oxc-minify: ^0.115.0
  pinia: ^3.0.4
  playwright: ^1.58.2
  reka-ui: ^2.8.2
  tailwind-merge: 3.4.0
  tailwindcss: ^4.2.1
  ts-pattern: ^5.9.0
  tw-animate-css: ^1.4.0
  type-fest: ^5.4.4
  typescript: ^5.9.3
  unplugin-turbo-console: ^2.3.0
  unplugin-vue-router: ^0.19.2
  vee-validate: ^4.15.1
  vite: ^7.3.1
  vite-plugin-vue-devtools: ^8.0.6
  vitepress: 2.0.0-alpha.15
  vitest: ^4.0.18
  vitest-browser-vue: ^2.0.2
  vue: ^3.5.29
  vue-codemirror6: ^1.4.2
  vue-router: ^5.0.3
  vue-sonner: 2.0.9
  vue-tsc: ^3.2.5
  wxt: ^0.20.18
  zod: ^4.3.6

catalogMode: prefer

ignoreWorkspaceRootCheck: true

overrides:
  vite: "catalog:"

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 1440
