packages:
  - extension
  - docs
  - packages/*

catalog:
  '@antfu/eslint-config': ^6.7.3
  '@codemirror/lang-json': ^6.0.2
  '@codemirror/theme-one-dark': ^6.1.3
  '@commitlint/cli': ^20.3.1
  '@commitlint/config-conventional': ^20.3.1
  '@commitlint/types': ^20.3.1
  '@egoist/tailwindcss-icons': 1.9.0
  '@fontsource-variable/inter': ^5.2.8
  '@fontsource-variable/jetbrains-mono': ^5.2.8
  '@formkit/auto-animate': ^0.9.0
  '@iconify-json/lucide': ^1.2.83
  '@tailwindcss/typography': 0.5.19
  '@tailwindcss/vite': ^4.1.18
  '@tanstack/vue-query': ^5.92.5
  '@tanstack/vue-virtual': ^3.13.18
  '@total-typescript/ts-reset': ^0.6.1
  '@tsconfig/node18': ^18.2.6
  '@tsconfig/node24': ^24.0.3
  '@types/node': ^24.10.6
  '@vitejs/plugin-vue': ^6.0.3
  '@vitejs/plugin-vue-jsx': ^5.1.3
  '@vitest/browser-playwright': ^4.0.16
  '@vue/tsconfig': ^0.8.1
  '@vueuse/core': 'catalog:'
  '@webext-core/messaging': ^2.3.0
  '@wxt-dev/auto-icons': ^1.1.0
  baseline-browser-mapping: ^2.9.14
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  codemirror: ^6.0.2
  codemirror-json-schema: ^0.8.1
  daisyui: 5.5.14
  es-toolkit: ^1.43.0
  eslint: ^9.39.2
  eslint-plugin-better-tailwindcss: ^3.8.0
  lefthook: ^2.0.13
  lucide-vue-next: 0.562.0
  oxc-minify: ^0.107.0
  pinia: ^3.0.4
  playwright: ^1.57.0
  reka-ui: 2.5.1
  tailwind-merge: 3.4.0
  tailwindcss: ^4.1.18
  ts-pattern: ^5.9.0
  tsdown: 0.18.4
  tw-animate-css: 1.4.0
  type-fest: ^5.3.1
  typescript: ^5.9.3
  unplugin-turbo-console: ^2.3.0
  unplugin-vue-components: 30.0.0
  unplugin-vue-router: ^0.19.2
  vee-validate: ^4.15.1
  vite-plugin-vue-devtools: ^8.0.5
  vitepress: 2.0.0-alpha.15
  vitest: ^4.0.16
  vitest-browser-vue: ^2.0.1
  vue: ^3.5.26
  vue-codemirror6: ^1.4.1
  vue-router: ^4.6.4
  vue-sonner: 2.0.9
  vue-tsc: 3.2.1
  wxt: ^0.20.13
  zod: ^4.3.5

catalogMode: prefer

ignoreWorkspaceRootCheck: true

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 1440
