packages:
  - extension
  - docs
  - packages/*

catalog:
  '@antfu/eslint-config': ^6.0.0
  '@codemirror/lang-json': ^6.0.2
  '@codemirror/theme-one-dark': ^6.1.3
  '@commitlint/cli': ^20.1.0
  '@commitlint/config-conventional': ^20.0.0
  '@commitlint/types': ^20.0.0
  '@egoist/tailwindcss-icons': 1.9.0
  '@fontsource-variable/inter': ^5.2.8
  '@fontsource-variable/jetbrains-mono': ^5.2.8
  '@formkit/auto-animate': ^0.9.0
  '@iconify-json/lucide': ^1.2.70
  '@tailwindcss/typography': 0.5.19
  '@tailwindcss/vite': ^4.1.14
  '@tanstack/vue-query': ^5.90.5
  '@tanstack/vue-virtual': ^3.13.12
  '@total-typescript/ts-reset': ^0.6.1
  '@types/node': ^24.8.1
  '@vitejs/plugin-vue': ^6.0.1
  '@vitejs/plugin-vue-jsx': ^5.1.1
  '@vitest/browser-playwright': ^4.0.3
  '@vueuse/core': ^13.9.0
  '@webext-core/messaging': ^2.3.0
  '@wxt-dev/auto-icons': ^1.1.0
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  codemirror: ^6.0.2
  codemirror-json-schema: ^0.8.1
  daisyui: 5.3.7
  es-toolkit: ^1.40.0
  eslint: ^9.38.0
  eslint-plugin-better-tailwindcss: ^3.7.10
  lefthook: ^2.0.0
  lucide-vue-next: 0.562.0
  oxc-minify: ^0.101.0
  pinia: ^3.0.3
  playwright: ^1.56.1
  reka-ui: 2.5.1
  tailwind-merge: 3.3.1
  tailwindcss: ^4.1.14
  tw-animate-css: 1.4.0
  type-fest: ^5.2.0
  typescript: ^5.9.3
  unplugin-turbo-console: ^2.2.0
  unplugin-vue-router: ^0.16.0
  vee-validate: ^4.15.1
  vite: npm:rolldown-vite@latest
  vite-plugin-vue-devtools: ^8.0.3
  vitepress: 2.0.0-alpha.15
  vitest: ^4.0.3
  vitest-browser-vue: ^2.0.0
  vue: ^3.5.22
  vue-codemirror6: ^1.4.1
  vue-router: ^4.6.3
  vue-sonner: ^2.0.9
  vue-tsc: ^3.1.0
  wxt: ^0.20.11
  zod: ^4.1.12

catalogMode: prefer

ignoreWorkspaceRootCheck: true

overrides:
  vite: 'catalog:'

shellEmulator: true

trustPolicy: no-downgrade
